name: CI

on:
  push:
    branches:
      - master
      - devel
  pull_request:
jobs:
  test:
    name: OTP-${{matrix.otp.version}}, PG-${{matrix.pg}}, PostGIS-${{matrix.postgis}}, OS-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-20.04"
        pg:
          - 12
        postgis:
          - 3
        otp:
          - version: "25.1"
            rebar3: "3.19"
          - version: "24.3"
            rebar3: "3.18"
          - version: "23.3"
            rebar3: "3.17"
          - version: "22.3"
            rebar3: "3.16"
          - version: "21.3"
            rebar3: "3.15"
          - version: "20.3"
            rebar3: "3.14"
    # env:
    #   PATH: ".:/usr/lib/postgresql/12/bin:$PATH"
    env:
      SHELL: /bin/sh            # needed for erlexec
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp.version}}
          rebar3-version: ${{matrix.otp.rebar3}}

      - name: Setup postgresql server with postgis
        run: sudo apt install postgresql-${{matrix.pg}} postgresql-contrib-${{matrix.pg}} postgresql-${{matrix.pg}}-postgis-${{matrix.postgis}} postgresql-${{matrix.pg}}-postgis-${{matrix.postgis}}-scripts

      - name: elvis
        run: make elvis

      - name: Common test, eunit, coverage
        run: PATH=$PATH:/usr/lib/postgresql/${{matrix.pg}}/bin/ make test

      - name: Upload CT logs artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ct_report_pg-${{matrix.pg}}_otp-${{matrix.otp.version}}
          path: |
            _build/test/logs/ct_run*/
            !_build/test/logs/ct_run*/datadir

      - name: Build docs
        run: make edoc

      - name: dialyzer
        run: make dialyzer
